create table "public"."cities" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "bundesland" text not null,
    "hebesatz" integer not null,
    "grundsteuerB" integer not null,
    "einwohner" integer not null,
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    "plz" text,
    "kreis" text,
    "regierungsbezirk" text,
    constraint "cities_pkey" primary key ("id")
);

-- Enable Row Level Security
alter table "public"."cities" enable row level security;

-- Create policy to allow public read access
create policy "Allow public read access"
on "public"."cities"
for select
to public
using (true);

-- Create indexes for better query performance
create index "cities_name_idx" on "public"."cities" using btree ("name");
create index "cities_bundesland_idx" on "public"."cities" using btree ("bundesland");
create index "cities_hebesatz_idx" on "public"."cities" using btree ("hebesatz");

-- Enable full text search
alter table "public"."cities" add column "name_search" tsvector
generated always as (to_tsvector('german', "name")) stored;

create index "cities_name_search_idx" on "public"."cities" using gin ("name_search");